connectivo/connectivo/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("fortnox.urls",namespace="fortnox")),
]

connectivo/fortnox/urls.py
from django.urls import path
from . import views

app_name = "fortnox"

urlpatterns = [

 path("",views.indexView.as_view(),name="index"),
 path("sync/",views.sync_view,name="sync"),
 path("article/post",views.post_article_view,name="post_article"),
 path("article/update/",views.update_article_view,name="update_article"),
 path("article/quick_update_article/<str:article_number>",views.update_article_view,name="quick_update_article"),
 path("invoice/create",views.create_invoice_view,name="create_invoice"),
 path("invoice/bookkeep",views.bookkeep_invoice_view,name="bookkeep_invoice"),
 path("invoice/all/<str:page>",views.invoices_view,name="all_invoices"),
 path("invoice/quick_bookkeep/<str:document_number>",views.bookkeep_invoice_view,name="quick_bookkeep"),
 path("invoice/last_synced/",views.last_synced_invoice_view,name="last_synced"),
 path("articles/all/<str:page>",views.articles_view,name="all_articles"),
 # path('<str:username>/post/<int:pk>/',views.userPostDetailView.as_view(),name="user_post_detail"),
 # path("<int:pk>/unsave/",views.postUnsaveView.as_view(),name="unsave"),
 # path('<int:pk>/save_for_future/',views.postSaveView.as_view(),name="save_for_future"),
 # path("all/",views.postListView.as_view(),name="post_list"),
 # path('<int:pk>/',views.PostDetailView.as_view(),name="post_detail"),
 # path("<str:username>/new/",views.CreatePostView.as_view(),name="create_post"),
 # path('<int:pk>/edit/',views.PostUpdateView.as_view(),name="edit_post"),
 # path('<str:username>/<int:pk>/delete/',views.PostDeleteView.as_view(),name="delete_post"),
 # path("<str:username>/saved/",views.savedListView.as_view(),name="view_saved"),
 # path('<int:pk>/comment/',views.add_comment_to_post,name="add_comment_to_post"),
 # path('<int:pk>/clap/',views.postClapView.as_view(),name="clap"),
 # path('cartegory/<str:name>/',views.cartegoryView.as_view(),name="cartegory"),
 # path('<int:pk>/publish/',views.post_publish,name="post_publish"),
 # path('<int:pk>/unpublish/',views.post_unpublish,name="post_unpublish"),
 # path('join_cartegory/<int:pk>/',views.join_cartegory_view,name="join_cartegory"),
 # path('leave_cartegory/<int:pk>/',views.leave_cartegory_view,name="leave_cartegory"),

]

connectivo/fortnox/models.py
from django.db import models

# Create your models here.

class lastSyncedRecord(models.Model):
    document_number = models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.document_number

connectivo/fortnox/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
from django.views import generic
from . import models
from django.contrib import messages

import os
import logging


import requests
import recurly
import json

recurly.SUBDOMAIN = 'connectivo'
recurly.API_KEY = 'edf04f55c7004393adb1e53fbae7bb42'

BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logging_dir = os.path.join(BASE_DIR,"logs","error_logging.log")
log_format = "%(asctime)s::%(levelname)s::%(name)s::%(filename)s::%(lineno)d::%(message)s"
logging.basicConfig(filename=logging_dir,format=log_format,filemode="w")





################################################################
###### this function handles the actual fortnox api calls#######
###############################################################
def fortnox_api_call(http_method,endpoint,data):
    try:
        r = http_method(
            url="https://api.fortnox.se/3/"+endpoint,
            headers = {
                        "Access-Token":"f895dac6-9b6a-4885-8daa-2041512f0911",
                        "Client-Secret":"I56Jh4yJSU",
                        "Content-Type":"application/json",
                        "Accept":"application/json",
                     },
            data = json.dumps(data)
                     )
        # print('Response HTTP Status Code : {status_code}'.format(status_code=r.status_code))
        return r
    except requests.exceptions.RequestException as e:
        # print('HTTP Request failed')
        logger=logging.getLogger()
        logger.setLevel(logging.DEBUG)
        logger.error(e)
####################################################################



# Create your views here.

######### the index page ##############
class indexView(generic.TemplateView):
    template_name="index.html"
######################################




#########################################################################
###### this view handles syncing fortnox account with recurly ###########
########################################################################
def sync_view(request):

    if request.method != "POST":

        def get_recurly_paid_invoices():
            try:
                return recurly.Invoice.all_paid(order='asc')
            except Exception as e:
                # print('HTTP Request failed')
                logger=logging.getLogger()
                logger.setLevel(logging.DEBUG)
                logger.error(e)


         # gets a dictionary of fortnox customer accounts
        def get_fortnox_customer_dict():
            r = fortnox_api_call(http_method=requests.get,endpoint='customers',data={})

            if r != None:
                customers_dict = json.loads(r.content)["Customers"]
                return customers_dict
            else:
                return r

        # gets a dictionary of fortnox articles
        def get_fortnox_articles_dict():
            r = fortnox_api_call(http_method=requests.get,endpoint='articles',data={})

            if r != None:
                articles_dict = json.loads(r.content)["Articles"]
                return articles_dict
            else:
                return r


        # creates a fortnox customer account
        def create_fortnox_customer_account(name):
            data = {
            "Customer": {
                "Name": name
                }
            }
            r = fortnox_api_call(http_method=requests.post,endpoint='customers',data=data)
            if r != None:
                return json.loads(r.content)["Customer"]["CustomerNumber"]
            else:
                return r


        # creates a fortnox article
        def create_fortnox_article(plan):
            data = {
            "Article": {
                 "Description":plan.name,
                # "ArticleNumber":str(int(plan.plan_code)+103),
                # "DirectCost":plan.unit_amount_in_cents,
                }
            }

            r = fortnox_api_call(http_method=requests.post,endpoint='articles',data=data)
            return r



        # creates a fortnox invoice
        def send_to_fortnox(invoice,plan,customer_number):

            data = {
                "Invoice": {
                "Currency":invoice.currency,
                     "InvoiceRows":[{
                        "ArticleNumber":plan.plan_code,
                        "Discount": invoice.discount_in_cents,
                        "Price": invoice.subtotal_in_cents,
                        "Unit": invoice.currency,
                     }],
                    "CustomerNumber": customer_number,
                    # "DueDate":invoice.attempt_next_collection_at,
                    # "InvoiceDate":invoice.created_at,
                    "TermsOfPayment":invoice.terms_and_conditions,
                    "Total":invoice.total_in_cents,
                    }
                }

            r = fortnox_api_call(http_method=requests.post,endpoint='invoices',data=data)

            return r

        # handles the syncing of fortnox and recurly accounts
        def sync_recurly_fortnox(last_synced):
            begin_sync = False
            # print(get_fortnox_articles_dict())
            fortnox_customer_dict = get_fortnox_customer_dict()

            recurly_paid_invoices = get_recurly_paid_invoices()

            for invoice in recurly_paid_invoices:

                if begin_sync == True:
                    account_exists_flag = False

                    recurly_customer_account = invoice.account()
                    subscriptions_pages = invoice.subscriptions()

                    for subscription in subscriptions_pages:
                        # print("this is the plan code: "+subscription.plan.plan_code)
                        try:
                            response = create_fortnox_article(subscription.plan)
                        except:
                            pass

                    for fortnox_customer in fortnox_customer_dict:
                        if fortnox_customer["Name"] == recurly_customer_account.first_name+" "+recurly_customer_account.last_name:
                            account_exists_flag = True

                    if account_exists_flag == True:
                            # print("customer already exits")
                            response = send_to_fortnox(invoice=invoice,plan=subscription.plan,customer_number = fortnox_customer["CustomerNumber"])
                    else:
                        customer_number = create_fortnox_customer_account(recurly_customer_account.first_name+" "+recurly_customer_account.last_name)
                        response = send_to_fortnox(invoice=invoice,plan=subscription.plan,customer_number=customer_number)

                if last_synced == None:
                    begin_sync=True
                elif invoice.invoice_number == last_synced.document_number:
                    begin_sync = True

                if invoice == recurly_paid_invoices[len(recurly_paid_invoices)-1]:
                    return invoice



        # this is the main sync_view function. it is not get_queryset() class method!
        def queryset():
            try:
                last_synced =  models.lastSyncedRecord.objects.all()
                if len(last_synced) > 0:
                    new_last_synced = sync_recurly_fortnox(last_synced=last_synced[0])
                    last_synced[0].document_number = new_last_synced.invoice_number
                    last_synced[0].save()
                else:
                    new_last_synced = sync_recurly_fortnox(last_synced=None)
                    models.lastSyncedRecord.objects.create(document_number = new_last_synced.invoice_number)
                messages.success(request, 'Synchronization completed! Your fortnox invoice database is up to date')
            except Exception as e:
                logger=logging.getLogger()
                logger.setLevel(logging.DEBUG)
                logger.error(e)

        queryset()
        return HttpResponseRedirect(reverse_lazy("fortnox:index"))




def post_article_view(request):
    if request.method == "POST":
        data = {
            "Article": {
                 "Description":request.POST.get("description"),
                # "ArticleNumber":str(int(plan.plan_code)+103),
                # "DirectCost":plan.unit_amount_in_cents,
            }
        }

        r = fortnox_api_call(http_method=requests.post,endpoint='articles',data=data)
        try:
            if r != None:
                if (str(r.status_code))[0] == "2":
                    messages.success(request, 'your article was created successfully! go to "All articles" to see all your articles')
                else:
                    messages.error(request, "unfortunately, for some reason, your article couldn't be created. please try again later")
        except Exception as e:
            # print('HTTP Request failed')
            logger=logging.getLogger()
            logger.setLevel(logging.DEBUG)
            logger.error(e)

        return HttpResponseRedirect(reverse_lazy("fortnox:index"))
    else:
        return render(request,'post_article.html')




def update_article_view(request,**kwargs):
    if request.method == "POST":
        data = {
            "Article": {
                 "Description":request.POST.get("description"),
                # "ArticleNumber":str(int(plan.plan_code)+103),
                # "DirectCost":plan.unit_amount_in_cents,
            }
        }

        r = fortnox_api_call(http_method=requests.put,endpoint="articles/"+request.POST.get("article_number"),data=data)

        try:
            if (str(r.status_code))[0] == "2":
                messages.success(request, 'your article was updated successfully! go to "All articles" to see all your articles')
            else:

connectivo/fortnox/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    {%block title%}
    {%endblock%}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  </head>
  <body>

    {%block header_footer%}
    {%endblock%}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

connectivo/fortnox/templates/bookkeep_invoice.html
{%extends 'header_footer.html'%}


{%block body%}
<div class="container">
  <form class="" action="{% url 'fortnox:bookkeep_invoice' %}" method="POST">
      <p class="text-muted">Bookkeep your invoice here</p>
      {%csrf_token%}
      <div class="form-group">
        <label for="document_number">Invoice Number*</label>
        <input class="form-control" id="document_number" type="text" name="document_number" value="" required>
        <small id="document_number" class="form-text text-muted">Ensure that this invoice exists</small>

      </div>
        <button type="submit" class="btn btn-success">Bookkeep Invoice</button>
  </form>
</div>

{%endblock%}

connectivo/fortnox/templates/create_invoice.html
{%extends 'header_footer.html'%}


{%block body%}
<div class="container">
  <form class="" action="{% url 'fortnox:create_invoice' %}" method="POST">
      <p class="text-muted">create an invoice here</p>
      {%csrf_token%}
      <div class="form-group">
        <label for="article_number">Article Number*</label>
        <input class="form-control" id="article_number" type="text" name="article_number" value="" required>
      </div>
      <div class="form-group">
        <label for="customer_number">Customer Number*</label>
        <input class="form-control" id="customer_number" type="text" name="customer_number" value="" required>
      </div>
      <div class="form-group">
        <label for="article_number">Unit*</label>
        <input class="form-control" id="unit" type="text" name="unit" value="" required>
      </div>
      <div class="form-group">
        <label for="currency">Currency*</label>
        <input class="form-control" id="currency" type="text" name="currency" value="" required>
        <small id="currency" class="form-text text-muted">you are adviced to use SEK. other currencies might not be supported</small>
      </div>
      <div class="form-group">
        <label for="price">Price*</label>
        <input class="form-control" id="price" type="text" name="price" value="" required>
      </div>
      <div class="form-group">
        <label for="discount">Discount*</label>
        <input class="form-control" id="discount" type="text" name="discount" value="">
      </div>
      <div class="form-group">
        <label for="due_date">Due Date*</label>
        <input class="form-control" id="due_date" type="text" name="due_date" value="" required>
        <small id="due_date" class="form-text text-muted">example: 2019-05-09</small>
      </div>
      <div class="form-group">
        <label for="invoice_date">Invoice Date*</label>
        <input class="form-control" id="invoice_date" type="text" name="invoice_date" value="" >
        <small id="invoice_date" class="form-text text-muted">example: 2019-05-09</small>
      </div>


        <button type="submit" class="btn btn-success">Create Invoice</button>
  </form>
</div>

{%endblock%}

connectivo/fortnox/templates/header_footer.html
{%extends "base.html" %}

{%block title%}
<title>Home</title>
{%endblock%}

{%block header_footer%}

<nav class="navbar navbar-expand-lg navbar-light bg-light text-white">
  <div class="container">
    <a class="navbar-brand font-weight-bolder" href="/">FortNoxClient <sup>ALPHA</sup></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropleft">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Articles</a>
        <div class="dropdown-menu dropdown-menu-left">
          <a class="dropdown-item" href="{%url 'fortnox:all_articles' page=1 %}">View Articles</a>
          <a class="dropdown-item" href="{%url 'fortnox:post_article' %}">Post Article</a>
          <a class="dropdown-item" href="{%url 'fortnox:update_article' %}">Update Article</a>
        </div>
      </li>
      <li class="nav-item dropleft">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Invoices</a>
      <div class="dropdown-menu dropdown-menu-left">
        <a class="dropdown-item" href="{%url 'fortnox:all_invoices' page=1 %}">View Invoices</a>
        <a class="dropdown-item" href="{%url 'fortnox:create_invoice' %}">Create Invoice</a>
        <a class="dropdown-item" href="{%url 'fortnox:bookkeep_invoice' %}">Bookkeep Invoice</a>
        <a class="dropdown-item" href="{%url 'fortnox:last_synced' %}">View Last Synced Invoice</a>
      </div>
    </li>
      </ul>
    </div>
  </div>
</nav>
{% include 'includes/_messages.html' %}<!-- This handles push messages that the backend might somethings need to push to the frontend Example an article post success message -->
{%block body%}

{%endblock%}



{%endblock%}

connectivo/fortnox/templates/index.html
{%extends 'header_footer.html'%}

{%block body%}
<div class="d-flex align-items-center justify-content-center" style="height:100vh;
background:url(../../static/images/continuous-integration.jpg) no-repeat center center;
background-size:cover;webkit-background-size:cover">
  <a href="{%url 'fortnox:sync' %}" class="btn btn-lg btn-primary"
   style="-webkit-box-shadow: 0px 2px 14px 2px rgba(0,0,0,0.75);
   -moz-box-shadow: 0px 2px 14px 2px rgba(0,0,0,0.75);
   box-shadow: 0px 2px 14px 2px rgba(0,0,0,0.75);">Sync Fortnox Account with Recurly</a>
</div>

{%endblock%}

connectivo/fortnox/templates/last_synced_invoice.html
{%extends 'header_footer.html'%}


{%block body%}
<div class="container">
  <br>
  <br>
  {%if invoice != None %}
  <table class="table table-striped">
    <tr>
      <th colspan="3" class="text-center font-size"><h4>Invoice Details</h4></th>
    </tr>
    <tr>
      <th>S/N</th>
      <th>Field</th>
      <th>Value</th>
    </tr>
    {%for field,value in invoice.items %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{field}}</td>
      <td>{{value}}</td>
    </tr>
    {%endfor%}
  </table>
  {%else%}
  <h2>You have not Synced your Account</h2>
  {%endif%}

</div>

{%endblock%}

connectivo/fortnox/templates/post_article.html
{%extends 'header_footer.html'%}


{%block body%}
<div class="container">
  <form class="" action="{% url 'fortnox:post_article' %}" method="POST">
      <p class="text-muted">Create new article here</p>
      {%csrf_token%}
      <div class="form-group">
        <label for="description">Article Description*</label>
        <textarea class="form-control" name="description" id="description" rows="2" cols="20" required></textarea>
      </div>
        <button type="submit" class="btn btn-success">Create Article</button>
  </form>  
</div>

{%endblock%}

connectivo/fortnox/templates/update_article.html
{%extends 'header_footer.html'%}


{%block body%}
<div class="container">
  <form class="" action="{% url 'fortnox:update_article' %}" method="POST">
      <p class="text-muted">update an existing article here</p>
      {%csrf_token%}
      <div class="form-group">
        <label for="article_number">Article Number*</label>
        {%if article_number != None %}
        <input class="form-control" id="article_number" type="text" name="article_number" value="{{article_number}}" required>
        {%else%}
        <input class="form-control" id="article_number" type="text" name="article_number" value="" required>
        {%endif%}
      </div>
      <div class="form-group">
        <label for="description">Article Description*</label>
        <textarea class="form-control" name="description" id="description" rows="2" cols="20" required></textarea>
      </div>
        <button type="submit" class="btn btn-success">Update Article</button>
  </form>
</div>

{%endblock%}

connectivo/fortnox/templates/view_articles.html
{%extends 'header_footer.html' %}


{%block body%}

<div class="container">

  <div class="float-right p-3">
    {%for page in pages%}
    <a href="{%url 'fortnox:all_articles' page=page %}" class="btn btn-sm btn-primary">{{page}}</a>
    {%endfor%}
  </div>

  <table class="table table-striped">
    <tr>
      <th>Article Number</th>
      <th>Description</th>
      <th>House Work</th>
      <th>Purchase Price</th>
      <th>Sales Price</th>
      <th>Quantity</th>
      <th>Vat</th>
      <th>Action</th>
    </tr>

    {%for article in articles %}
    <tr>
      <td>{{article.ArticleNumber}}</td>
      <td>{{article.Description}}</td>
      <td>{{article.HouseWork}}</td>
      <td>{{article.PurchasePrice}}</td>
      <td>{{article.SalesPrice}}</td>
      <td>{{article.Quantity}}</td>
      <td>{{article.Vat}}</td>
      <td><a href="{%url 'fortnox:quick_update_article' article_number=article.ArticleNumber %}" class="btn btn-success btn-sm">Update</a></td>
    </tr>
    {%endfor%}
  </table>

  <div class="float-right p-3">
    {%for page in pages%}
    <a href="{%url 'fortnox:all_articles' page=page %}" class="btn btn-sm btn-primary">{{page}}</a>
    {%endfor%}
  </div>

</div>

{%endblock%}

connectivo/fortnox/templates/view_invoices.html
{%extends 'header_footer.html' %}


{%block body%}


<div class="container">

  <div class="float-right p-3">
    {%for page in pages%}
    <a href="{%url 'fortnox:all_invoices' page=page %}" class="btn btn-lg btn-primary">{{page}}</a>
    {%endfor%}
  </div>

  <table class="table table-striped">
    <tr>
      <th>Document Number</th>
      <th>Customer Name</th>
      <th>Customer Number</th>
      <th>Currency</th>
      <th>Due Date</th>
      <th>Invoice Date</th>
      <th>Booked</th>
      <th>Action</th>
    </tr>

    {%for invoice in invoices %}
    <tr>
      <td>{{invoice.DocumentNumber}}</td>
      <td>{{invoice.CustomerName}}</td>
      <td>{{invoice.CustomerNumber}}</td>
      <td>{{invoice.Currency}}</td>
      <td>{{invoice.DueDate}}</td>
      <td>{{invoice.InvoiceDate}}</td>
      <td>{{invoice.Booked}}</td>
      <td><a href="{%url 'fortnox:quick_bookkeep' document_number=invoice.DocumentNumber %}" class="btn btn-success btn-sm">Bookkeep</a></td>
    </tr>
    {%endfor%}
  </table>

  <div class="float-right p-3">
    {%for page in pages%}
    <a href="{%url 'fortnox:all_invoices' page=page %}" class="btn btn-lg btn-primary">{{page}}</a>
    {%endfor%}
  </div>

</div>


{%endblock%}